import { appendRefreshCookies, LiveAccessError, liveSession } from "@/server/supabase-session";
import { SupabaseError, supabaseRequest } from "@/server/supabase";
import { sendSmsText, smsConfigured, SmsError } from "@/server/sms";

export const dynamic="force-dynamic";
type Json=Record<string,unknown>;
export async function GET(request:Request){try{const session=await liveSession(request);if(session.identity.role==="client")throw new LiveAccessError(403,"SMS sending is available to staff only.");return appendRefreshCookies(Response.json({ok:true,configured:smsConfigured()}),session.refreshed,request);}catch(error){return apiError(error);}}
export async function POST(request:Request){try{const session=await liveSession(request);if(session.identity.role==="client")throw new LiveAccessError(403,"SMS sending is available to staff only.");const body=await request.json() as Json;if(body.action!=="send_message")throw new InputError("Unsupported SMS action.");const id=uuid(body.messageId,"Message");const rows=await supabaseRequest<Json[]>(`/rest/v1/sms_messages?select=*&id=eq.${id}&limit=1`,{method:"GET"},session.accessToken);const message=rows[0];if(!message)throw new LiveAccessError(403,"That SMS is not available to you.");if(!["draft","failed"].includes(String(message.delivery_state)))throw new InputError("Only a draft or failed SMS can be sent.");try{const sent=await sendSmsText({to:String(message.recipient),body:String(message.body)});await patch(id,{provider_message_id:sent.id,delivery_state:sent.status==="queued"?"queued":"sent",sent_at:new Date().toISOString(),provider_error:null},session.accessToken);await supabaseRequest("/rest/v1/audit_events",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({organisation_id:session.identity.organisationId,actor_id:session.identity.profileId,action:"sms.sent",resource_type:"sms_message",resource_id:id,case_id:message.case_id,summary:"Sent case-linked SMS"})},session.accessToken);return appendRefreshCookies(Response.json({ok:true,providerMessageId:sent.id}),session.refreshed,request);}catch(error){await patch(id,{delivery_state:"failed",provider_error:error instanceof Error?error.message.slice(0,1000):"Provider failure"},session.accessToken).catch(()=>undefined);throw error;}}catch(error){return apiError(error);}}
async function patch(id:string,value:Json,token:string){await supabaseRequest(`/rest/v1/sms_messages?id=eq.${id}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(value)},token);}
function uuid(value:unknown,label:string){const parsed=typeof value==="string"?value.trim():"";if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(parsed))throw new InputError(`${label} is invalid.`);return parsed;}
class InputError extends Error{}
function apiError(error:unknown){if(error instanceof InputError)return Response.json({ok:false,error:error.message},{status:400});if(error instanceof LiveAccessError)return Response.json({ok:false,error:error.message},{status:error.status});if(error instanceof SmsError)return Response.json({ok:false,error:error.message},{status:error.status});if(error instanceof SupabaseError)return Response.json({ok:false,error:"The database rejected this SMS action."},{status:error.status>=400&&error.status<500?error.status:503});console.error(error);return Response.json({ok:false,error:"The SMS action could not be completed."},{status:500});}
