import {expect,test,type Page} from '@playwright/test';
const officer='c0000000-0000-4000-8000-000000000003';
const caseId='e0000000-0000-4000-8000-000000000001';
async function signIn(page:Page,email:string){await page.context().clearCookies();await page.goto('/');await page.locator('input[name=email]').fill(email);await page.locator('input[name=password]').fill('irrelevant');await page.getByRole('button',{name:/^sign in$/i}).click();await expect(page.locator('.appShell')).toBeVisible({timeout:25000});}
async function staffManagement(page:Page){await page.getByRole('button',{name:'Open case navigation',exact:true}).click();await page.locator('.sidebar').getByRole('button',{name:'Staff management',exact:true}).click();await expect(page.getByRole('heading',{name:'Staff accounts',exact:true})).toBeVisible();}
test('case tasks complete with comments and notifications; function access can be revoked',async({page})=>{
 test.setTimeout(100000);const title=`Case task ${Date.now()}`;
 await signIn(page,'owner@maximus.test');
 await page.goto(`/?case=${caseId}&tab=tasks`);
 const board=page.getByRole('region',{name:'Case tasks',exact:true});await expect(board).toBeVisible({timeout:25000});
 await board.getByRole('button',{name:'Create task',exact:true}).click();const editor=page.getByRole('dialog',{name:'Create task',exact:true});
 await editor.locator('input[name=title]').fill(title);await editor.locator('textarea[name=description]').fill('Confirm documents and record the outcome.');await editor.locator('select[name=assignedTo]').selectOption(officer);await editor.getByRole('button',{name:'Save task',exact:true}).click();await expect(editor).toHaveCount(0);
 let card=board.locator('article').filter({has:page.getByRole('heading',{name:title,exact:true})});await expect(card).toBeVisible();await card.getByRole('button',{name:'Comments',exact:true}).click();
 const comments=page.getByRole('dialog',{name:title,exact:true});await comments.getByRole('textbox',{name:'Add comment',exact:true}).fill('Documents confirmed.');await comments.getByRole('button',{name:'Post comment',exact:true}).click();await expect(comments.getByText('Documents confirmed.',{exact:true})).toBeVisible();await comments.getByRole('button',{name:'Close comments'}).click();
 await signIn(page,'officer@maximus.test');await page.goto(`/?case=${caseId}&tab=tasks`);await expect(board).toBeVisible({timeout:25000});card=board.locator('article').filter({has:page.getByRole('heading',{name:title,exact:true})});await card.getByRole('button',{name:'Mark completed',exact:true}).click();await expect(card.getByRole('button',{name:'Reopen task',exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.setViewportSize({width:1440,height:1000});
 const notes=await page.request.get('/api/crm/operations?view=notifications');expect((await notes.json()).data.some((n:{title:string})=>n.title===`Task completed: ${title}`)).toBeTruthy();
 await signIn(page,'owner@maximus.test');const ownerNotes=await page.request.get('/api/crm/operations?view=notifications');expect((await ownerNotes.json()).data.some((n:{title:string})=>n.title===`Task completed: ${title}`)).toBeTruthy();
 try{
 await staffManagement(page);const row=page.getByRole('row').filter({hasText:'Olivia Officer'});await row.locator('summary').click();await row.getByRole('button',{name:'Function access',exact:true}).click();const access=page.getByRole('dialog',{name:'Olivia Officer',exact:true});await access.getByRole('group',{name:'Study permission',exact:true}).getByRole('switch',{name:'Tasks',exact:true}).uncheck();await access.getByRole('group',{name:'Direct Visa permission',exact:true}).getByRole('switch',{name:'Tasks',exact:true}).uncheck();await access.getByRole('group',{name:'Study permission',exact:true}).getByRole('switch',{name:'Accounts',exact:true}).uncheck();await access.getByRole('group',{name:'Direct Visa permission',exact:true}).getByRole('switch',{name:'Accounts',exact:true}).uncheck();await access.getByRole('button',{name:'Save access',exact:true}).click();await expect(access).toHaveCount(0);
 await signIn(page,'officer@maximus.test');expect((await page.request.get('/api/crm/tasks')).status()).toBe(403);expect((await page.request.post('/api/crm/workspace',{data:{action:'invoice'}})).status()).toBe(403);
 await page.getByRole('button',{name:'Open case navigation',exact:true}).click();await expect(page.locator('.sidebar').getByRole('button',{name:'Accounts',exact:true})).toHaveCount(0);
 }finally{await signIn(page,'owner@maximus.test');const reset=await page.request.post('/api/crm/admin',{data:{action:'set_function_access',profileId:officer,access:null}});expect(reset.ok()).toBeTruthy();}
});
test('account creation applies Enquiries and Applications only from first sign-in',async({page})=>{
 test.setTimeout(80000);await page.setViewportSize({width:1600,height:1100});const email=`limited.${Date.now()}@maximus.test`;await signIn(page,'owner@maximus.test');await staffManagement(page);
 await page.getByRole('button',{name:'Add staff member',exact:true}).click();const form=page.locator('form').filter({has:page.locator('input[name=displayName]')});await form.locator('input[name=displayName]').fill('Limited Admissions');await form.locator('input[name=email]').fill(email);await form.locator('input[name=mobile]').fill('+61 400 123 456');await form.locator('select[name=timezone]').selectOption('Asia/Dhaka');await form.getByRole('button',{name:'Turn all off',exact:true}).click();await form.getByRole('switch',{name:'Study Abroad permission',exact:true}).check();const study=form.getByRole('group',{name:'Study permission',exact:true});await study.getByRole('switch',{name:'Enquiries',exact:true}).check();await study.getByRole('switch',{name:'Applications',exact:true}).check();await study.getByRole('switch',{name:'View applications',exact:true}).check();await form.screenshot({path:'/tmp/maximus-staff-permissions-desktop.png'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await form.screenshot({path:'/tmp/maximus-staff-permissions-phone.png'});await page.setViewportSize({width:1440,height:1000});await form.getByRole('button',{name:'Create staff account',exact:true}).click();await expect(form).toHaveCount(0,{timeout:20000});
 const savedAccount=await page.request.get('/api/crm/admin');const created=(await savedAccount.json()).profiles.find((person:{email:string})=>person.email===email);expect(created.staff_details).toEqual({mobile:'+61 400 123 456',timezone:'Asia/Dhaka'});await signIn(page,email);await expect(page.locator('.journeyList-enquiries')).toBeVisible({timeout:25000});await page.getByRole('button',{name:'Open case navigation',exact:true}).click();const nav=page.locator('.sidebar');await expect(nav.getByRole('button',{name:'Enquiries',exact:true})).toBeVisible();await expect(nav.getByRole('button',{name:'Applications',exact:true})).toBeVisible();await expect(nav.getByRole('button',{name:'Accounts',exact:true})).toHaveCount(0);await expect(nav.getByRole('button',{name:'Staff management',exact:true})).toHaveCount(0);
 expect((await page.request.get('/api/crm/tasks')).status()).toBe(403);expect((await page.request.get('/api/crm/admin')).status()).toBe(403);expect((await page.request.post('/api/crm/operations',{data:{action:'record_export'}})).status()).toBe(403);
});
