"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {useFunctionAccess} from "./function-access-context";
import {useOverlayFocus} from "./use-overlay-focus";
import {canUse,roleForLevel,type FunctionAccess} from "@/lib/function-access";
import styles from "./task-board.module.css";
type Task={id:string;case_id:string|null;title:string;description:string|null;assigned_to:string;assigned_by:string;created_by:string;created_at:string;updated_at:string;due_at:string|null;completed_at:string|null;completed_by:string|null;status:string;priority:string;task_type:string};
type Staff={id:string;display_name:string;branch_id:string|null;level:string;active:boolean;function_access?:FunctionAccess|null};
type Comment={id:string;author_id:string;body:string;created_at:string};
const date=(value:string|null)=>value?new Date(value).toLocaleString():"No due date";
async function request(body:unknown){const response=await fetch("/api/crm/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Task could not be saved.");return result;}
export function TaskBoard({caseId,branchId,onChanged}:{caseId?:string;branchId?:string|null;onChanged?:()=>Promise<void>|void}){
 const allowed=useFunctionAccess();
 const [tasks,setTasks]=useState<Task[]>([]),[staff,setStaff]=useState<Staff[]>([]),[profileId,setProfileId]=useState("");
 const [counts,setCounts]=useState<Record<string,number>>({}),[count,setCount]=useState(0),[page,setPage]=useState(1);
 const [filters,setFilters]=useState({status:"all",type:"all",search:"",priority:"",assignedTo:"",createdFrom:"",createdTo:"",dueFrom:"",dueTo:""});
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 const [selected,setSelected]=useState<string[]>([]),[editor,setEditor]=useState<Task|"new"|null>(null),[comments,setComments]=useState<Task|null>(null);
 const [now,setNow]=useState(()=>Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const query=new URLSearchParams({...filters,page:String(page),...(caseId?{caseId}:{})}).toString();
 useEffect(()=>{const controller=new AbortController();let live=true;const load=async()=>{setLoading(true);setError("");try{const res=await fetch(`/api/crm/tasks?${query}`,{cache:"no-store",signal:controller.signal});const result=await res.json();if(!res.ok)throw new Error(result.error||"Tasks could not be loaded.");if(live){setTasks(result.data);setStaff(result.staff);setProfileId(result.profileId);setCount(result.count??result.data.length);setCounts(result.counts);setSelected([]);}}catch(e){if(live&&!controller.signal.aborted)setError(e instanceof Error?e.message:"Tasks could not be loaded.");}finally{if(live)setLoading(false);}};void load();return()=>{live=false;controller.abort();};},[query,revision]);
 const name=(id:string|null)=>staff.find(p=>p.id===id)?.display_name||(id?"Staff member":"Unassigned");
 const eligible=staff.filter(p=>p.active&&canUse({role:roleForLevel(p.level),functionAccess:p.function_access},"work")&&(!branchId||p.branch_id===branchId||["super_admin","platform_owner"].includes(p.level)));
 const changed=async()=>{setRevision(v=>v+1);try{localStorage.setItem("maximus.workspaceRefresh",crypto.randomUUID());}catch{}await onChanged?.();};
 const run=async(body:unknown)=>{if(busy)return;setBusy(true);setError("");try{await request(body);await changed();}catch(e){setError(e instanceof Error?e.message:"Task could not be saved.");}finally{setBusy(false);}};
 const bulk=(operation:string,assignedTo?:string)=>{if(operation==="delete"&&!confirm(`Delete ${selected.length} selected tasks and their comments?`))return;void run({action:"bulk",operation,assignedTo,items:tasks.filter(t=>selected.includes(t.id)).map(t=>({id:t.id,expected:t.updated_at}))});};
 const filter=(key:keyof typeof filters,value:string)=>{setFilters(v=>({...v,[key]:value}));setPage(1);};
 return <section className={styles.board} aria-label={caseId?"Case tasks":"All tasks"}>
  <header className={styles.heading}><div><small>KEEP EVERY FOLLOW-UP IN VIEW</small><h2>{caseId?"Tasks for this case":"Tasks"}</h2><p>Assign work, track progress and record what was completed.</p></div><div><button disabled={loading} onClick={()=>setRevision(v=>v+1)}>Refresh</button><button className="primaryButton" onClick={()=>setEditor("new")}>Create task</button></div></header>
  <div className={styles.counts}>{[["all","All tasks"],["open","Pending"],["completed","Completed"],["overdue","Overdue"]].map(([key,label])=><button key={key} aria-pressed={filters.status===key} onClick={()=>filter("status",key)}><strong>{counts[key]??0}</strong><span>{label}</span></button>)}</div>
  <div className={styles.filters}><label>Search title<input value={filters.search} onChange={e=>filter("search",e.target.value)} placeholder="Find a task…"/></label><label>Task view<select value={filters.type} onChange={e=>filter("type",e.target.value)}><option value="all">All tasks</option><option value="mine">Assigned to me</option><option value="self">Self tasks</option></select></label><label>Priority<select value={filters.priority} onChange={e=>filter("priority",e.target.value)}><option value="">All priorities</option>{["low","medium","high","critical"].map(v=><option key={v}>{v}</option>)}</select></label><label>Assigned to<select value={filters.assignedTo} onChange={e=>filter("assignedTo",e.target.value)}><option value="">All staff</option>{staff.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><details><summary>Date filters</summary><div className={styles.dates}>{([ ["createdFrom","Created from"],["createdTo","Created to"],["dueFrom","Due from"],["dueTo","Due to"]] as const).map(([key,label])=><label key={key}>{label}<input type="date" value={filters[key]} onChange={e=>filter(key,e.target.value)}/></label>)}</div></details><button onClick={()=>{setPage(1);setFilters({status:"all",type:"all",search:"",priority:"",assignedTo:"",createdFrom:"",createdTo:"",dueFrom:"",dueTo:""});}}>Reset filters</button></div>
  {error&&<p role="alert" className={styles.error}>{error}</p>}
  {selected.length>0&&<div className={styles.bulk}><strong>{selected.length} selected</strong><button disabled={busy} onClick={()=>bulk("completed")}>Complete selected</button><button disabled={busy} onClick={()=>bulk("open")}>Reopen</button><select aria-label="Assign selected tasks" value="" disabled={busy||!allowed("action_assign")} onChange={e=>bulk("assign",e.target.value)}><option value="">Assign to…</option>{eligible.map(p=><option value={p.id} key={p.id}>{p.display_name}</option>)}</select>{allowed("action_bulk_delete")&&<button disabled={busy} onClick={()=>bulk("delete")}>Delete</button>}<button onClick={()=>setSelected([])}>Clear</button></div>}
  {loading?<p role="status">Loading tasks…</p>:<><label className={styles.selectAll}><input type="checkbox" checked={tasks.length>0&&selected.length===tasks.length} onChange={e=>setSelected(e.target.checked?tasks.map(t=>t.id):[])}/>Select this page</label>{tasks.length===0&&<p className={styles.empty}>No tasks match these filters. Create a task to record the next action.</p>}{tasks.map(task=><article key={task.id} className={`${styles.card} ${task.status==="completed"?styles.complete:""}`}><div className={styles.cardTitle}><input aria-label={`Select ${task.title}`} type="checkbox" checked={selected.includes(task.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,task.id]:v.filter(id=>id!==task.id))}/><h3>{task.title}</h3><span className={styles.badge}>{task.status==="completed"?"Completed":"Pending"}</span><span className={styles.badge}>{task.priority}</span></div>{task.description&&<p className={styles.description}>{task.description}</p>}<dl className={styles.meta}><div><dt>Assigned to</dt><dd>{name(task.assigned_to)}</dd></div><div><dt>Assigned by</dt><dd>{name(task.assigned_by)}</dd></div><div><dt>Created</dt><dd>{date(task.created_at)} · {name(task.created_by)}</dd></div><div><dt>Due</dt><dd className={task.status!=="completed"&&task.due_at&&new Date(task.due_at).getTime()<now?styles.error:""}>{date(task.due_at)}</dd></div>{task.completed_at&&<div><dt>Completed by</dt><dd>{name(task.completed_by)} · {date(task.completed_at)}</dd></div>}</dl><footer><button disabled={busy} onClick={()=>void run({action:"status",id:task.id,expected:task.updated_at,values:{status:task.status==="completed"?"open":"completed"}})}>{task.status==="completed"?"Reopen task":"Mark completed"}</button><button onClick={()=>setComments(task)}>Comments</button><button onClick={()=>setEditor(task)}>Edit / assign</button>{!caseId&&task.case_id&&<a href={`/?case=${task.case_id}&tab=tasks`}>Open student case</a>}<button disabled={busy||!allowed("action_delete")} onClick={()=>{if(confirm(`Delete “${task.title}” and its comments?`))void run({action:"delete",id:task.id,expected:task.updated_at});}}>Delete</button></footer></article>)}</>}
  <div className={styles.pagination}><span>{count} tasks · Page {page} of {Math.max(1,Math.ceil(count/50))}</span><button disabled={page<=1||loading} onClick={()=>setPage(v=>v-1)}>Previous</button><button disabled={page*50>=count||loading} onClick={()=>setPage(v=>v+1)}>Next</button></div>
  {editor&&<TaskEditor key={editor==="new"?"new":editor.id} task={editor==="new"?undefined:editor} caseId={caseId} profileId={profileId} staff={eligible} close={()=>setEditor(null)} saved={async()=>{setEditor(null);await changed();}}/>}
  {comments&&<TaskComments task={comments} name={name} close={()=>setComments(null)}/>}
 </section>;
}
function TaskEditor({task,caseId,profileId,staff,close,saved}:{task?:Task;caseId?:string;profileId:string;staff:Staff[];close:()=>void;saved:()=>Promise<void>}){
 const allowed=useFunctionAccess();
 const [id]=useState(()=>task?.id??crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState("");const ref=useRef<HTMLElement|null>(null);useOverlayFocus(true,ref,()=>{if(!busy)close();});
 return <div className={styles.backdrop}><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="task-editor-title" ref={ref} tabIndex={-1}><header><h2 id="task-editor-title">{task?"Edit task":"Create task"}</h2><button type="button" aria-label="Close task" disabled={busy} onClick={close}>×</button></header><form onSubmit={async e=>{e.preventDefault();if(busy)return;const data=new FormData(e.currentTarget);setBusy(true);setError("");try{await request({action:task?"edit":"create",id,expected:task?.updated_at,values:{...Object.fromEntries(data),caseId:task?.case_id??caseId??null,due:data.get("due")?new Date(String(data.get("due"))).toISOString():null}});await saved();}catch(e){setError(e instanceof Error?e.message:"Task could not be saved.");}finally{setBusy(false);}}}><label>Title *<input name="title" required maxLength={250} defaultValue={task?.title}/></label><label>Description<textarea name="description" rows={4} maxLength={10000} defaultValue={task?.description??""}/></label><div className={styles.formGrid}><label>Assigned to<select name="assignedTo" disabled={!allowed("action_assign")} defaultValue={task?.assigned_to??profileId}>{staff.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label><label>Priority<select name="priority" defaultValue={task?.priority??"medium"}>{["low","medium","high","critical"].map(v=><option key={v}>{v}</option>)}</select></label><label>Due date<input type="datetime-local" name="due" defaultValue={task?.due_at?new Date(new Date(task.due_at).getTime()-new Date(task.due_at).getTimezoneOffset()*60000).toISOString().slice(0,16):""}/></label><label>Task type<select name="taskType" defaultValue={task?.task_type??"case_work"}>{["case_work","follow_up","documents","application","visa","finance","internal"].map(v=><option key={v}>{v}</option>)}</select></label></div>{error&&<p role="alert" className={styles.error}>{error}</p>}<footer><button type="button" disabled={busy} onClick={close}>Cancel</button><button className="primaryButton" disabled={busy}>{busy?"Saving…":"Save task"}</button></footer></form></section></div>;
}
function TaskComments({task,name,close}:{task:Task;name:(id:string)=>string;close:()=>void}){
 const [comments,setComments]=useState<Comment[]>([]),[page,setPage]=useState(1),[count,setCount]=useState(0),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const ref=useRef<HTMLElement|null>(null),commentId=useRef<string|null>(null);useOverlayFocus(true,ref,()=>{if(!busy)close();});
 const load=useCallback(async()=>{const r=await fetch(`/api/crm/tasks?taskId=${task.id}&page=${page}`,{cache:"no-store"});const result=await r.json();if(!r.ok)throw new Error(result.error||"Comments could not be loaded.");setComments(result.data);setCount(result.count??result.data.length);},[task.id,page]);
 useEffect(()=>{let live=true;void Promise.resolve().then(load).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[load]);
 return <div className={styles.backdrop}><section className={styles.dialog} ref={ref} role="dialog" aria-modal="true" aria-labelledby="task-comments-title" tabIndex={-1}><header><div><small>TASK COMMENTS</small><h2 id="task-comments-title">{task.title}</h2></div><button aria-label="Close comments" disabled={busy} onClick={close}>×</button></header>{comments.map(c=><article className={styles.comment} key={c.id}><strong>{name(c.author_id)}</strong><small>{date(c.created_at)}</small><p>{c.body}</p></article>)}{comments.length===0&&<p>No comments yet.</p>}<div className={styles.pagination}><button disabled={page===1} onClick={()=>setPage(v=>v-1)}>Previous</button><span>Page {page}</span><button disabled={page*50>=count} onClick={()=>setPage(v=>v+1)}>Next</button></div><form onSubmit={async e=>{e.preventDefault();if(busy||!body.trim())return;setBusy(true);setError("");commentId.current??=crypto.randomUUID();try{await request({action:"comment",id:task.id,values:{id:commentId.current,body}});setBody("");commentId.current=null;await load();}catch(e){setError(e instanceof Error?e.message:"Comment could not be saved.");}finally{setBusy(false);}}}><label>Add comment<textarea required maxLength={5000} rows={3} value={body} onChange={e=>{setBody(e.target.value);commentId.current=null;}}/></label>{error&&<p role="alert" className={styles.error}>{error}</p>}<footer><button className="primaryButton" disabled={busy||!body.trim()}>{busy?"Posting…":"Post comment"}</button></footer></form></section></div>;
}
