-- Maximus CRM Next: relational core for Supabase/PostgreSQL.
create extension if not exists pgcrypto;
create type public.user_level as enum ('platform_owner','super_admin','branch_admin','manager','staff','partner','student');
create type public.case_health as enum ('healthy','attention','critical','closed');
create type public.document_state as enum ('requested','uploaded','under_review','verified','rejected','expired','archived');
create type public.invoice_state as enum ('draft','issued','part_paid','paid','overdue','void','refunded');

create table public.organisations (id uuid primary key default gen_random_uuid(), name text not null, workspace_domains text[] not null default '{}', timezone text not null default 'Australia/Melbourne', created_at timestamptz not null default now());
create table public.branches (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, name text not null, code text not null, country_code text not null, active boolean not null default true, unique (organisation_id, code));
create table public.profiles (id uuid primary key references auth.users on delete cascade, organisation_id uuid not null references public.organisations on delete cascade, branch_id uuid references public.branches, display_name text not null, email text not null, level public.user_level not null default 'staff', department text, active boolean not null default true, created_at timestamptz not null default now(), unique (organisation_id, email));
create table public.roles (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, name text not null, level public.user_level not null, data_scope text not null default 'assigned', system_role boolean not null default false, unique (organisation_id, name));
create table public.permissions (id uuid primary key default gen_random_uuid(), role_id uuid not null references public.roles on delete cascade, resource text not null, action text not null, field_mask jsonb not null default '{}', unique(role_id,resource,action));
create table public.profile_roles (profile_id uuid references public.profiles on delete cascade, role_id uuid references public.roles on delete cascade, branch_id uuid references public.branches, primary key(profile_id,role_id,branch_id));

create table public.clients (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, branch_id uuid references public.branches, crm_id text not null, first_name text not null, last_name text not null, preferred_name text, email text, mobile text, date_of_birth date, nationality text, passport_number_encrypted text, owner_id uuid references public.profiles, source text, current_lifecycle text not null default 'enquiry', drive_folder_id text, drive_sync_state text not null default 'pending', custom_fields jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, unique(organisation_id,crm_id));
create index clients_org_name_idx on public.clients(organisation_id,last_name,first_name);
create index clients_org_email_idx on public.clients(organisation_id,email);
create table public.dependants (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, client_id uuid not null references public.clients on delete cascade, relationship text not null, full_name text not null, date_of_birth date, passport_number_encrypted text, drive_folder_id text, details jsonb not null default '{}');
create table public.enquiries (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, client_id uuid references public.clients on delete cascade, branch_id uuid references public.branches, assigned_to uuid references public.profiles, source text, campaign text, priority text not null default 'medium', status text not null default 'new', score integer not null default 0, next_follow_up_at timestamptz, lost_reason text, created_at timestamptz not null default now(), converted_at timestamptz);

create table public.workflow_templates (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, name text not null, service_type text not null, destination_country text, version integer not null default 1, active boolean not null default true, configuration jsonb not null default '{}', created_by uuid references public.profiles, created_at timestamptz not null default now());
create table public.workflow_stages (id uuid primary key default gen_random_uuid(), template_id uuid not null references public.workflow_templates on delete cascade, name text not null, position integer not null, department text, sla_hours integer, entry_rules jsonb not null default '{}', exit_rules jsonb not null default '{}', automations jsonb not null default '[]', unique(template_id,position));
create table public.cases (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, client_id uuid not null references public.clients on delete cascade, branch_id uuid references public.branches, case_number text not null, service_type text not null, workflow_template_id uuid references public.workflow_templates, current_stage_id uuid references public.workflow_stages, owner_id uuid references public.profiles, supervisor_id uuid references public.profiles, health public.case_health not null default 'healthy', priority text not null default 'medium', progress smallint not null default 0 check(progress between 0 and 100), target text, next_action text, due_at timestamptz, stage_entered_at timestamptz not null default now(), opened_at timestamptz not null default now(), closed_at timestamptz, outcome text, custom_fields jsonb not null default '{}', unique(organisation_id,case_number));
create index cases_org_stage_idx on public.cases(organisation_id,current_stage_id,health);
create index cases_owner_due_idx on public.cases(owner_id,due_at) where closed_at is null;
create table public.case_stage_history (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, case_id uuid not null references public.cases on delete cascade, from_stage_id uuid references public.workflow_stages, to_stage_id uuid not null references public.workflow_stages, changed_by uuid references public.profiles, reason text, entered_at timestamptz not null default now(), exited_at timestamptz);
create table public.education_applications (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, case_id uuid not null references public.cases on delete cascade, institution text not null, course text not null, campus text, intake text, application_reference text, status text not null default 'draft', submitted_at timestamptz, offer_received_at timestamptz, coe_received_at timestamptz, deadline_at timestamptz, details jsonb not null default '{}');
create table public.visa_matters (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, case_id uuid not null references public.cases on delete cascade, destination_country text not null, visa_subclass text, visa_stream text, lodgement_reference text, status text not null default 'assessment', agent_id uuid references public.profiles, lodged_at timestamptz, decision_at timestamptz, outcome text, current_visa_expiry date, details jsonb not null default '{}');

create table public.tasks (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, case_id uuid references public.cases on delete cascade, client_id uuid references public.clients on delete cascade, title text not null, description text, assigned_to uuid references public.profiles, assigned_by uuid references public.profiles, department text, priority text not null default 'medium', status text not null default 'open', due_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now());
create table public.case_notes (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, case_id uuid not null references public.cases on delete cascade, author_id uuid references public.profiles, body text not null, visibility text not null default 'case_team', mentions uuid[] not null default '{}', created_at timestamptz not null default now());
create table public.documents (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, client_id uuid not null references public.clients on delete cascade, case_id uuid references public.cases on delete cascade, dependant_id uuid references public.dependants on delete cascade, document_type text not null, display_name text not null, state public.document_state not null default 'requested', drive_file_id text, drive_folder_id text, mime_type text, size_bytes bigint, version integer not null default 1, expires_on date, requested_by uuid references public.profiles, uploaded_by uuid references public.profiles, verified_by uuid references public.profiles, verified_at timestamptz, rejection_reason text, checksum text, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create index documents_case_state_idx on public.documents(case_id,state);
create table public.drive_jobs (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, client_id uuid references public.clients on delete cascade, document_id uuid references public.documents on delete cascade, operation text not null, payload jsonb not null default '{}', status text not null default 'queued', attempts integer not null default 0, available_at timestamptz not null default now(), last_error text, created_at timestamptz not null default now());

create table public.mailbox_connections (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, profile_id uuid references public.profiles on delete cascade, email text not null, provider text not null default 'gmail', connection_type text not null default 'personal', token_reference text, sync_cursor text, active boolean not null default true, unique(organisation_id,email));
create table public.email_threads (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, client_id uuid references public.clients on delete cascade, case_id uuid references public.cases on delete cascade, provider_thread_id text, subject text not null, assigned_to uuid references public.profiles, status text not null default 'open', awaiting_party text, last_message_at timestamptz, unique(organisation_id,provider_thread_id));
create table public.email_messages (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, thread_id uuid not null references public.email_threads on delete cascade, provider_message_id text, sender text not null, recipients text[] not null default '{}', cc text[] not null default '{}', direction text not null, body_preview text, sent_at timestamptz, delivery_state text, created_by uuid references public.profiles, metadata jsonb not null default '{}');

create table public.invoices (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, client_id uuid references public.clients, case_id uuid references public.cases, invoice_number text not null, invoice_type text not null, currency text not null default 'AUD', subtotal numeric(14,2) not null default 0, tax numeric(14,2) not null default 0, total numeric(14,2) not null default 0, paid numeric(14,2) not null default 0, state public.invoice_state not null default 'draft', issued_on date, due_on date, created_by uuid references public.profiles, unique(organisation_id,invoice_number));
create table public.payments (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, invoice_id uuid not null references public.invoices on delete cascade, amount numeric(14,2) not null, currency text not null, method text, reference text, paid_at timestamptz not null default now(), recorded_by uuid references public.profiles);
create table public.commission_claims (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations on delete cascade, application_id uuid references public.education_applications, partner_name text, institution text, currency text not null default 'AUD', expected_amount numeric(14,2) not null default 0, received_amount numeric(14,2) not null default 0, status text not null default 'expected', due_on date, agreement_version text, details jsonb not null default '{}');
create table public.audit_events (id bigint generated always as identity primary key, organisation_id uuid not null references public.organisations on delete cascade, actor_id uuid references public.profiles, action text not null, resource_type text not null, resource_id text, case_id uuid references public.cases, summary text, before_data jsonb, after_data jsonb, ip_hash text, occurred_at timestamptz not null default now());
create index audit_org_time_idx on public.audit_events(organisation_id,occurred_at desc);

create or replace function public.current_organisation_id() returns uuid language sql stable security definer set search_path=public as $$ select organisation_id from public.profiles where id = auth.uid() and active = true $$;
do $$ declare t text; begin foreach t in array array['branches','profiles','roles','clients','dependants','enquiries','workflow_templates','cases','case_stage_history','education_applications','visa_matters','tasks','case_notes','documents','drive_jobs','mailbox_connections','email_threads','email_messages','invoices','payments','commission_claims','audit_events'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy tenant_isolation on public.%I for all to authenticated using (organisation_id = public.current_organisation_id()) with check (organisation_id = public.current_organisation_id())',t); end loop; end $$;
-- Production hardening adds branch, assignment, action and field policies.
